sudo: required
services:
- docker
branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
env:
  global:
  - DOCKER_IMAGE_NAME=kellerwilliams/image-proxy-microservice
  - DEPLOYMENT_NAME=image-proxy
  - COMMIT=${TRAVIS_COMMIT::8}
before_script:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
- mkdir -p /home/travis/.kube/
- echo "$kw_dev_us_east1_KUBECONFIG" | base64 --decode > /home/travis/.kube/kubeconfig-kw-dev-us-east1
- echo "$kw_qa_us_east1_KUBECONFIG" | base64 --decode > /home/travis/.kube/kubeconfig-kw-qa-us-east1
- echo "$kw_prod_us_east1_KUBECONFIG" | base64 --decode > /home/travis/.kube/kubeconfig-kw-prod-us-east1
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

script:
- docker build -t $DOCKER_IMAGE_NAME:$COMMIT .
after_success:
- if [[ -n "$TRAVIS_TAG" ]]; then
  docker tag $DOCKER_IMAGE_NAME:$COMMIT $DOCKER_IMAGE_NAME:$TRAVIS_TAG ;
  docker push $DOCKER_IMAGE_NAME:$TRAVIS_TAG ; fi
- docker push $DOCKER_IMAGE_NAME:$COMMIT ; 
- if [[ $TRAVIS_BRANCH  == "develop" && $TRAVIS_PULL_REQUEST == "false" ]]; then kubectl
  --kubeconfig=/home/travis/.kube/kubeconfig-kw-dev-us-east1 set image deployment/$DEPLOYMENT
  nginx=$DOCKER_IMAGE_NAME:$COMMIT ; fi
- if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then kubectl
  --kubeconfig=/home/travis/.kube/kubeconfig-kw-qa-us-east1 set image deployment/$DEPLOYMENT
  nginx=$DOCKER_IMAGE_NAME:$COMMIT ; fi
